# Generated by Django 4.1.6 on 2023-02-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_car_accepted"),
        ("users", "0003_remove_billingaddress_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.ManyToManyField(
                blank=True, related_name="cart", through="users.CartItem", to="main.car"
            ),
        ),
    ]
