# Generated by Django 4.1.6 on 2023-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="profile.png", upload_to=""),
        ),
    ]
