# Generated by Django 4.1.6 on 2023-02-25 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_remove_brand_model_color_car_color_reservation_car_and_more"),
        ("users", "0007_alter_user_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="car",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="start_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="user",
            name="cart_end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cart_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 25, 9, 11, 8, 94051, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="user",
            name="cart",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.ForeignKey(
                default=100, on_delete=django.db.models.deletion.CASCADE, to="main.car"
            ),
            preserve_default=False,
        ),
    ]
