# Generated by Django 4.1.6 on 2023-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_cartitem_unique_together_remove_cartitem_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cart_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="cart_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
