# Generated by Django 4.1.6 on 2023-02-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_reservation_created_at"),
        ("users", "0009_alter_user_cart_end_date_alter_user_cart_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.car"
            ),
        ),
    ]
