# Generated by Django 4.1.6 on 2023-02-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_cart_pick_up_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_owner",
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=150)),
                ("image", models.ImageField(default="profile.png", upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "about",
                    models.TextField(blank=True, max_length=500, verbose_name="about"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
