# Generated by Django 4.1.6 on 2023-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_is_owner_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="image",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.CharField(default="www.facebook.com", max_length=100),
            preserve_default=False,
        ),
    ]
