# Generated by Django 4.1.6 on 2023-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_company_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="address",
            new_name="city",
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default="egypt", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="governate",
            field=models.CharField(default="cairo", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="place",
            field=models.CharField(default="6 october", max_length=150),
            preserve_default=False,
        ),
    ]
