# Generated by Django 4.1.6 on 2023-02-13 03:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_car_plate_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand_model",
            name="transmission",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="manual",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CarReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                5, "Can't rate car with more than 5 starts"
                            )
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "car")},
            },
        ),
    ]
