# Generated by Django 4.1.6 on 2023-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_brand_model_transmission_car_mileage_carreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand_model",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("natural gas", "Natural Gas"),
                    ("electric", "Electric"),
                ],
                default="petrol",
                max_length=150,
            ),
        ),
    ]
