# Generated by Django 4.1.6 on 2023-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_brand_model_fuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
