# Generated by Django 4.1.6 on 2023-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_blogreview_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="img",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
