# Generated by Django 4.1.6 on 2023-02-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_blog_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="luggage",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="seats",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
