# Generated by Django 4.1.6 on 2023-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_car_luggage_car_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="added_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
