# Generated by Django 4.1.6 on 2023-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_remove_car_luggage_remove_car_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand_model",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
