# Generated by Django 4.1.6 on 2023-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_reservation_pick_up_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
