# Generated by Django 4.1.6 on 2023-02-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationitem",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_cars",
                to="main.car",
            ),
        ),
    ]
