# Generated by Django 4.1.6 on 2023-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_reservationitem_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
