# Generated by Django 4.1.6 on 2023-02-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_contactus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand_model",
            name="color",
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(default="red", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="car",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="main.car",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ReservationItem",
        ),
    ]
