# Generated by Django 4.1.6 on 2023-02-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_remove_brand_model_color_car_color_reservation_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carreview",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="main.car",
            ),
        ),
    ]
