# Generated by Django 4.1.6 on 2023-02-26 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_carreview_added_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 26, 8, 51, 46, 295312, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
