# Generated by Django 4.1.6 on 2023-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_reservation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="address",
            field=models.CharField(default="desouk", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(default="admin", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(default="admin", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone_number",
            field=models.CharField(default="+201000000000", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="postcode",
            field=models.CharField(default=33611, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="city",
            field=models.CharField(default="desouk", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="country",
            field=models.CharField(default="egypt", max_length=20),
            preserve_default=False,
        ),
    ]
