# Generated by Django 4.1.6 on 2023-02-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_reservation_address_reservation_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created",
        ),
    ]
