# Generated by Django 4.1.6 on 2023-02-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_company_email_remove_company_image_and_more"),
        ("main", "0029_alter_reservation_options_remove_reservation_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="owner",
        ),
        migrations.AddField(
            model_name="car",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
            preserve_default=False,
        ),
    ]
