# Generated by Django 4.1.6 on 2023-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_car_owner_car_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="visits",
            field=models.IntegerField(default=0),
        ),
    ]
