# Generated by Django 4.1.6 on 2023-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_car_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(default="placeholder.png", upload_to=""),
        ),
        migrations.DeleteModel(
            name="Car_imgs",
        ),
    ]
